#!/usr/bin/env python

"""
Configger

Merge, substitute variables, and compress multiple cloud-config
files into one.

   # Example input YAML data
   #=========================

   # If output-file is null, stdout will be used.
   output-file: user-data.yml

   # Use 'base64' here to encode the entire output as one line
   # of base64 (useful in an AWS launch-template)
   output-encoding: null

   variable-mapping:
     key: value
     key: value
     ...

   cloud-configs:
   - file.yml
   - file.yml
     ...

Environment variables (useful for troubleshooting):
  DEBUG
        Turn on debugging output.
  NOCOMPRESS
        Do not compress or encode the merged cloud-config.

Copyright (c) 2016,2019, Kris Feldmann
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above
     copyright notice, this list of conditions and the following
     disclaimer in the documentation and/or other materials provided
     with the distribution.

  3. Neither the name of the copyright holder nor the names of its
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


import sys
import os
import gzip
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.encoders import encode_base64 # for the message body
from base64 import standard_b64encode # for the optional b64 output
import io

import yaml


def usage():
    "Print the usage statement and exit."
    sys.stderr.write("Usage: cf [-s] cloud-configs.yml\n")
    sys.stderr.write("    -s\n")
    sys.stderr.write( \
        "       The argument is a YAML string, rather than a filename.\n")
    raise SystemExit(1)

def _i(message):
    "Print an INFO message to stderr."
    sys.stderr.write('INFO: %s\n' % message)
    return None

def _e(message):
    "Print an ERROR message to stderr and exit."
    sys.stderr.write('ERROR: %s\n' % message)
    raise SystemExit(1)

def _w(message):
    "Print a WARN (warning) message to stderr."
    sys.stderr.write('WARN: %s\n' % message)
    return None

def _d(message):
    """
    If the DEBUG environment variable has been set,
    print a DEBUG message to stderr.
    """
    if os.environ.get('DEBUG') is not None:
        sys.stderr.write('DEBUG: %s\n' % message)
    return None

def __merge(src, dst):
    """
    Recursively merge "src" data structure into "dst" data structure.
    """
    if isinstance(src, (dict)) and isinstance(dst, (dict)):
        for (k, v) in src.items():
            if k in dst:
                __merge(src[k], dst[k])
            else:
                dst[k] = v
    elif isinstance(src, (list)) and isinstance(dst, (list)):
        dst.extend(src)
    elif isinstance(src, (str)) and isinstance(dst, (str)):
        dst = src
    else:
        _w('Merge not handling: type(src)==%s, type(dst)==%s\n' \
          % (src, dst))
    return None

def merge_cc(cloud_config_list):
    "Returns a YAML string representing one merged cloud-config."
    if not cloud_config_list:
        return None
    merged = {}
    for ccfname in cloud_config_list:
        try:
            f = open(
                os.path.expandvars(
                    os.path.expanduser(
                        ccfname)), 'r')
        except IOError:
            _e('Failed to open cloud-config file, "%s"' % ccfname)
        try:
            data = yaml.load(f, Loader=yaml.FullLoader)
        except yaml.YAMLError as ex:
            f.close()
            _e('Problem parsing cloud-config data: "%s": %s' \
               % (ccfname, str(ex)))
        f.close()
        __merge(data, merged)
    return '#cloud-config\n%%YAML 1.1\n---\n%s' % \
            yaml.dump(merged, default_flow_style=False)

def varsub(cc, vmap):
    "Substitute variables in a cloud-config string."
    for k in vmap:
        cc = cc.replace(k, vmap[k])
    return cc

def compress2(in_data):
    """
    Package cloud-config document as a gzip'd MIME document.
    If resulting data is not smaller than the original,
    return the original instead.
    """
    _d("Starting compress2()")
    start_size = len(in_data)
    out_buf = io.BytesIO()

    # The last arg to GzipFile() is a timestamp, representing the
    # last-modified time of the source file. Tools like Terraform
    # use a checksum of the overall output of configger to determine
    # whether anything has changed. If this timestamp is not
    # provided, the gzip library will use the current time. This causes
    # Terraform to always think the user-data has changed, so it
    # wants to re-make the launch configuration. To prevent this
    # we use a fixed 0.0 timestamp here.
    zipper = gzip.GzipFile(None, 'wb', 9, out_buf, 0.0)
    zipper.write(in_data.encode())
    zipper.close()
    c = out_buf.getvalue()

    combined_message = MIMEMultipart(boundary="=")
    filename = "user-data.gz"
    sub_message = MIMEBase("application", "gzip")
    sub_message.set_payload(c)
    encode_base64(sub_message)
    sub_message.add_header('Content-Disposition',
                           'attachment',
                           filename=filename)
    combined_message.attach(sub_message)

    out_data = combined_message.as_string(unixfrom=False)
    end_size = len(out_data)
    _d("Input size: %d" % start_size)
    _d("Output size: %d" % end_size)
    ratio = float(end_size)/float(start_size)
    if ratio < 1.0:
        _d("Savings: %d%%" % int(100.0 - 100.0*ratio))
        return out_data
    _d("No savings. Returning unmodified input data.")
    return in_data

def main():
    "Run the program."
    if '-?' in sys.argv \
            or '-h' in sys.argv \
            or '--help' in sys.argv:
        usage()
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        usage()
    if sys.argv[1] == '-s':
        if len(sys.argv) == 3:
            cc_list_st = sys.argv[2]
            cc_list_dict = yaml.load(cc_list_st, Loader=yaml.FullLoader)
        else:
            usage()
    else:
        if len(sys.argv) == 2:
            fd = open(
                os.path.expandvars(
                    os.path.expanduser(sys.argv[1])
                ),
                'r')
            cc_list_dict = yaml.load(fd, Loader=yaml.FullLoader)
            fd.close()
        else:
            usage()

    cc_list = cc_list_dict.get('cloud-configs', [])
    var_map = cc_list_dict.get('variable-mapping', {})
    out_file = cc_list_dict.get('output-file', None)
    out_enc = cc_list_dict.get('output-encoding', None)
    if out_enc in ('None', 'none', 'Null', 'null'):
        out_enc = None
    if out_enc not in (None, 'base64'):
        _e('Unsupported output encoding type. Supported types are: null, "base64"')

    # merge multiple cloud-config files
    cc_str = merge_cc(cc_list)
    # perform variable substitution
    cc_str = varsub(cc_str, var_map)
    # compress
    if os.environ.get('NOCOMPRESS') is None:
        cc_str = compress2(cc_str)
    # encode
    if os.environ.get('NOCOMPRESS') is None:
        if out_enc == 'base64':
            cc_str = standard_b64encode(cc_str.encode('utf8'))
    # output
    if out_file:
        fd = open(
            os.path.expandvars(
                os.path.expanduser(
                    out_file)), 'w')
        fd.write(cc_str)
        fd.close()
    else:
        sys.stdout.write('%s' % cc_str) # no newline

if __name__ == "__main__":
    main()
